// Keeps the Gyan module registry honest, and exports it for the Python
// pipeline.
//
// The registry exists so a module is declared once instead of in four places
// (hub grid, search chips, `build.py --modules`, coming-soon gating). That only
// holds if something enforces it — otherwise the Dart list and the pipeline's
// idea of which modules exist drift apart silently, and `--modules ramayana`
// quietly builds nothing.
//
// Running this test writes content/tools/modules.json, so the export is a side
// effect of the check rather than a step someone has to remember.

import 'dart:convert';
import 'dart:io';

import 'package:divyavaani/app/router/app_router.dart';
import 'package:divyavaani/app/theme/category_colors.dart';
import 'package:divyavaani/features/gyan/gyan_modules.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';

/// Every literal path the router declares, with `:params` intact.
List<String> _declaredRoutes(List<RouteBase> routes, [String prefix = '']) {
  final out = <String>[];
  for (final r in routes) {
    if (r is GoRoute) {
      final path = r.path.startsWith('/')
          ? r.path
          : '$prefix/${r.path}'.replaceAll('//', '/');
      if (path.isNotEmpty) out.add(path);
      out.addAll(_declaredRoutes(r.routes, path));
    } else if (r is ShellRouteBase) {
      out.addAll(_declaredRoutes(r.routes, prefix));
    }
  }
  return out;
}

/// True when [candidate] is served by [pattern], treating `:param` as a
/// single-segment wildcard.
bool _matches(String pattern, String candidate) {
  final p = pattern.split('/');
  final c = candidate.split('/');
  if (p.length != c.length) return false;
  for (var i = 0; i < p.length; i++) {
    if (p[i].startsWith(':')) continue;
    if (p[i] != c[i]) return false;
  }
  return true;
}

void main() {
  final declared = _declaredRoutes(appRouter.configuration.routes);

  group('Gyan module registry', () {
    test('ids are unique and pipeline-safe', () {
      final ids = gyanModules.map((m) => m.id).toList();
      expect(ids.toSet().length, ids.length, reason: 'duplicate module id');
      for (final id in ids) {
        // Ids cross the Dart/Python boundary as `--modules a,b,c` and as
        // search_docs.kind, so anything exotic breaks one side or the other.
        expect(RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(id), isTrue,
            reason: "module id '$id' must be lower_snake_case");
      }
    });

    test('every module is bilingual', () {
      for (final m in gyanModules) {
        expect(m.titleHi.trim(), isNotEmpty, reason: '${m.id} has no Hindi title');
        expect(m.blurbHi.trim(), isNotEmpty, reason: '${m.id} has no Hindi blurb');
      }
    });

    test('every module resolves to a gradient', () {
      for (final m in gyanModules) {
        expect(m.style(CategoryColors.standard).gradient, hasLength(2),
            reason: '${m.id} has no usable tile gradient');
      }
    });

    test('shipped modules must have a registered route', () {
      for (final m in gyanModules.where((m) => m.shipped)) {
        expect(declared.any((d) => _matches(d, m.route)), isTrue,
            reason: "module '${m.id}' is marked shipped but its route "
                "'${m.route}' is not registered in app_router.dart");
      }
    });

    test('unshipped modules are not silently reachable', () {
      // A module whose screen does not exist yet should not have a live route:
      // that combination means the hub shows "coming soon" while a deep link
      // opens a half-built screen.
      for (final m in gyanModules.where((m) => !m.shipped)) {
        final live = declared.any((d) => _matches(d, m.route));
        expect(live, isFalse,
            reason: "route '${m.route}' is registered but module '${m.id}' is "
                "still marked shipped: false — flip the flag in the same commit "
                "that lands the screen");
      }
    });
  });

  test('exports content/tools/modules.json for the build pipeline', () {
    final payload = {
      '_comment': 'GENERATED by test/gyan_modules_test.dart from '
          'lib/features/gyan/gyan_modules.dart. Do not edit by hand. '
          'build.py reads this to validate --modules.',
      'modules': [
        for (final m in gyanModules)
          {
            'id': m.id,
            'route': m.route,
            'title_en': m.titleEn,
            'backing_table': m.backingTable,
            'spec': m.spec,
            'shipped': m.shipped,
          }
      ],
    };

    final file = File('content/tools/modules.json');
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(
        '${const JsonEncoder.withIndent('  ').convert(payload)}\n');

    expect(file.existsSync(), isTrue);
    expect(gyanModules, isNotEmpty);
  });

  test('routes.txt export covers every declared route', () {
    // validate.py check 13 uses this to prove that every route emitted into
    // search_docs / path_steps actually exists. Regenerating it here means a
    // route rename can never silently break every indexed deep link.
    final sorted = declared.toSet().toList()..sort();
    final file = File('content/tools/routes.txt');
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(
      '# GENERATED by test/gyan_modules_test.dart from appRouter.\n'
      '# One route pattern per line; :params match a single segment.\n'
      '${sorted.join('\n')}\n',
    );
    expect(sorted, contains('/'));
  });
}
