// The contract between the search index and the app.
//
// The index is built by content/tools/common.py at content-build time; queries
// are folded by lib/features/search/search_fold.dart at runtime. If those two
// disagree about what a word folds to, the app asks for tokens the index does
// not contain and search returns nothing — with no error, no crash, and no clue
// as to why.
//
// test/fixtures/fold_fixtures.json is GENERATED by Python:
//     py -m content.tools.gen_fold_fixtures
// so this test is comparing Dart against the real, authoritative behaviour
// rather than against a second hand-written copy of the rules.

import 'dart:convert';
import 'dart:io';

import 'package:divyavaani/features/search/search_fold.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final file = File('test/fixtures/fold_fixtures.json');
  final fixtures =
      jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;

  group('foldVariants matches the Python index builder', () {
    final cases = fixtures['foldVariants'] as Map<String, dynamic>;

    test('fixture file is present and non-trivial', () {
      expect(file.existsSync(), isTrue,
          reason: 'run: py -m content.tools.gen_fold_fixtures');
      expect(cases.length, greaterThan(40));
    });

    for (final entry in cases.entries) {
      final input = entry.key;
      final expected = (entry.value as List).cast<String>();
      test('fold(${_label(input)})', () {
        expect(foldVariants(input), expected,
            reason: 'Dart and Python disagree on "$input". '
                'Search would silently return nothing for this term.');
      });
    }
  });

  group('tokenize matches the Python index builder', () {
    final cases = fixtures['tokenize'] as Map<String, dynamic>;
    for (final entry in cases.entries) {
      final expected = (entry.value as List).cast<String>();
      test('tokenize(${_label(entry.key)})', () {
        expect(tokenize(entry.key), expected);
      });
    }
  });

  group('the properties users actually depend on', () {
    test('all four spellings of Krishna reach the same token', () {
      // The single most important behaviour in search: someone typing the
      // English, the Devanagari, or either transliteration must land in the
      // same place.
      for (final s in ['Krishna', 'kṛṣṇa', 'KRISHNA', 'krishna']) {
        expect(foldVariants(s), contains('krishna'), reason: 'failed for "$s"');
      }
      expect(foldVariants('कृष्ण'), ['कृष्ण'],
          reason: 'Devanagari must survive verbatim — stripping its matras '
              'as combining marks would destroy the word');
    });

    test('diacritic-free typists still hit diacritic content', () {
      // Indexing 'kṛṣṇa' emits both forms, so a query for the bare spelling
      // still finds it.
      expect(foldVariants('kṛṣṇa'), contains('krsna'));
      expect(foldVariants('Viṣṇu'), containsAll(['vishnu', 'visnu']));
    });

    test('ś and ṣ both become sh, matching common spelling', () {
      expect(foldVariants('Śiva'), contains('shiva'));
      expect(foldVariants('Shiva'), contains('shiva'));
    });

    test('English prose is not mangled', () {
      // Guards the decision NOT to map c -> ch: that would be closer to popular
      // transliteration but would turn "concept" into "chonchept", and the fold
      // runs over English text too.
      expect(fold('concept'), 'concept');
      expect(fold('Celestial'), 'celestial');
    });

    test('empty and junk input folds away rather than throwing', () {
      expect(foldVariants(''), isEmpty);
      expect(foldVariants('   '), isEmpty);
      expect(foldVariants('!!!'), isEmpty);
    });
  });
}

String _label(String s) => s.trim().isEmpty ? '<blank>' : s;
